branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.3
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=OSX
    - TEST_TYPE=tvOS
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
install:
- |
  brew update
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = OSX ] || [ "$TEST_TYPE" = tvOS ]; then
    bundle install
  elif [ "$TEST_TYPE" = Carthage ]; then    
    brew install carthage || brew upgrade carthage
  fi
script:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    set -o pipefail
    xcodebuild -project SocketRocket.xcodeproj -scheme "SocketRocket" -sdk iphonesimulator build test | xcpretty -c
  elif [ "$TEST_TYPE" = OSX ]; then
    set -o pipefail
    xcodebuild -project SocketRocket.xcodeproj -scheme "SocketRocket-OSX" -sdk macosx build | xcpretty -c
  elif [ "$TEST_TYPE" = tvOS ]; then
    set -o pipefail
    xcodebuild -project SocketRocket.xcodeproj -scheme "SocketRocket-tvOS" -sdk appletvsimulator build | xcpretty -c
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint SocketRocket.podspec
    pod lib lint --use-libraries SocketRocket.podspec
  elif [ "$TEST_TYPE" = Carthage ]; then
    carthage build --no-skip-current
  fi
